---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform/ee-minimal-rhel9:2.17.14

dependencies:
  galaxy:
    collections:
      - name: amazon.aws
        version: "10.1.2"

options:
  package_manager_path: /usr/bin/microdnf
