---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform/ee-minimal-rhel9:2.17.14

dependencies:
  galaxy: requirements.yml

options:
  package_manager_path: /usr/bin/microdnf

additional_build_files:
  - src: /home/eames/.ansible/ansible.cfg
    dest: configs

additional_build_steps:
  prepend_base:
    # Make ansible dir becauser ADD ~/.ansible.cfg not working
    - RUN mkdir -p /etc/ansible/
    - RUN curl "https://releases.hashicorp.com/terraform/1.14.0/terraform_1.14.0_linux_amd64.zip" -o "terraform.zip" && unzip terraform.zip && mv terraform /usr/local/bin/ && rm terraform.zip
    - RUN terraform --version
  prepend_galaxy:
    - ADD _build/configs/ansible.cfg /etc/ansible/ansible.cfg
